# Generated by Django 4.0.6 on 2022-09-14 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('date_of_berith', models.DateField()),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mouny_moved', models.IntegerField()),
                ('resone', models.CharField(max_length=60)),
                ('date', models.DateField()),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debtor', to='debt_meneger.partner')),
                ('lowaner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loaner', to='debt_meneger.partner')),
            ],
        ),
    ]
