# Generated by Django 4.0.6 on 2022-09-26 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debt_meneger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='lowaner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lowaner', to='debt_meneger.partner'),
        ),
    ]
